backend electro shop
MykolaRudenko7/electro-shop-backend pull request #2
Opened 2023-12-18 09:51 UTC by MykolaRudenko7

2023-12-19 09:49 UTC, yurii-kozlov requested changes

2023-12-19 09:49 UTC, yurii-kozlov commented on src/controllers/cart-controller.js
> +import ApiError from '../exceptions/api-error.js'
it would be good to set absolute imports

2023-12-19 09:49 UTC, yurii-kozlov commented on src/controllers/cart-controller.js
> +  async shippingHandler(req, res, next) {
```suggestion
  async handleShipping(req, res, next) {
```
Also indicate please in the name of the method what is shipped

2023-12-19 09:49 UTC, yurii-kozlov commented on src/controllers/products-controller.js
> +import ApiError from '../exceptions/api-error.js'
please set up absolute imports

2023-12-19 09:49 UTC, yurii-kozlov commented on src/data/config.js
> +export const appAddresses = {
```suggestion
export const appEndpoints = {
```

please move it into a separate file as it is not a config

2023-12-19 09:49 UTC, yurii-kozlov commented on src/controllers/user-controller.js
> +      const validateErrors = validationResult(req)
```suggestion
      const validationErrors = validationResult(req)
```

2023-12-19 09:49 UTC, yurii-kozlov commented on src/controllers/user-controller.js
> +      await UserService.activate(activationLink)
does this method activate the account? Then it should be renamed to smth like 'confirm account' or 'activate account'

2023-12-19 09:49 UTC, yurii-kozlov commented on src/middlewares/error-middleware.js
> +  console.log(err)
pls remove logging to console here

2023-12-19 09:49 UTC, yurii-kozlov commented on src/routes/index.js
> +router.post(
pls move validation into a separate file 'userValidation.js'

2023-12-19 09:49 UTC, yurii-kozlov commented on src/data/config.js
> +  accessTokenExpires: process.env.ACCESS_TOKEN_EXPIRES_IN,
```suggestion
  accessTokenExpirationTime: process.env.ACCESS_TOKEN_EXPIRES_IN,
```

2023-12-19 09:49 UTC, yurii-kozlov commented on src/data/config.js
> +  refreshTokenExpires: process.env.REFRESH_TOKEN_EXPIRES_IN,
```suggestion
  refreshTokenExpirationTime: process.env.REFRESH_TOKEN_EXPIRES_IN,
```

2023-12-19 09:49 UTC, yurii-kozlov commented on src/service/token-service.js
> +        .json({ success: true, message: message, user, accessToken, refreshToken })
why do you need to pass tokens in the body? It seem that you pass them to cookies already

2023-12-19 09:49 UTC, yurii-kozlov commented on src/service/token-service.js
> +  async handleSetResponse(res, userData, message) {
```suggestion
  async sendAuthResponseWithTokens(res, userData, message) {
```

2023-12-19 09:49 UTC, yurii-kozlov commented on src/service/user-service.js
> +  async signInUser(email, password) {
It seems that this method violates the SRP, that's why you need to create different functions for different responsibilities. Please consider creating separate methods:

- getUserByEmail
- handleInvalidUser
- handleIncorrectPassword
- resetLockAndLoginAttempts

2023-12-20 10:48 UTC, yurii-kozlov approved these changes

2023-12-20 10:48 UTC, yurii-kozlov commented on src/controllers/cart-controller.js
> +  async handleShipping(req, res, next) {
maybe 'handleProductsShipping' would be a better naming

2023-12-20 10:48 UTC, yurii-kozlov commented on src/service/user-service.js
> +    const userExistsByEmail = await User.findOne({ email })
```suggestion
    const doesUserExistByEmail = await User.findOne({ email })
```

2023-12-20 10:48 UTC, yurii-kozlov commented on src/service/user-service.js
> +    const userExistsByPhone = await User.findOne({ mobileNumber })
```suggestion
    const doesUserExistByPhone = await User.findOne({ mobileNumber })
```

2023-12-20 10:48 UTC, yurii-kozlov commented on src/utils/userValidation.js
> +export const userValidationRules = () => {
Do you need to create a function for this?

2023-12-22 09:11 UTC, RuchkoVlad approved these changes

2023-12-22 09:12 UTC, RuchkoVlad approved these changes

2023-12-25 18:10 UTC, merged